// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:quiz_code/main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      deviceType = 'Web';
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        deviceType = 'Android';
        return android;
      case TargetPlatform.iOS:
        deviceType = 'iOS';
        return ios;
      case TargetPlatform.macOS:
        deviceType = 'macOS';
        return macos;
      case TargetPlatform.windows:
        deviceType = 'Windows';
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoGH64wmP0_-h5IxNocnItbWcUmxJE7VU',
    appId: '1:568688432259:web:7c52e2d5eb6071341737b6',
    messagingSenderId: '568688432259',
    projectId: 'lazziapp',
    authDomain: 'lazziapp.firebaseapp.com',
    storageBucket: 'lazziapp.firebasestorage.app',
    measurementId: 'G-W5YEKYG7GF',
    //database 
    databaseURL: 'https://lazziapp-quiz-code-slot.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUEJ2c8HqU1RwrCExrn_1MXKNlMeX22Og',
    appId: '1:568688432259:android:932e3c4e568fd1021737b6',
    messagingSenderId: '568688432259',
    projectId: 'lazziapp',
    storageBucket: 'lazziapp.firebasestorage.app',
    databaseURL: 'https://lazziapp-quiz-code-slot.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMc0lap4U53j8nzq_vqFYuacKOmn54Ffg',
    appId: '1:568688432259:ios:a56892c903ed230d1737b6',
    messagingSenderId: '568688432259',
    projectId: 'lazziapp',
    storageBucket: 'lazziapp.firebasestorage.app',
    androidClientId: '568688432259-sn20agp9q0ms6n7bf844dm5qoh5mj6sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizCode',
    databaseURL: 'https://lazziapp-quiz-code-slot.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMc0lap4U53j8nzq_vqFYuacKOmn54Ffg',
    appId: '1:568688432259:ios:a56892c903ed230d1737b6',
    messagingSenderId: '568688432259',
    projectId: 'lazziapp',
    storageBucket: 'lazziapp.firebasestorage.app',
    androidClientId: '568688432259-sn20agp9q0ms6n7bf844dm5qoh5mj6sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizCode',
    databaseURL: 'https://lazziapp-quiz-code-slot.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoGH64wmP0_-h5IxNocnItbWcUmxJE7VU',
    appId: '1:568688432259:web:d85df5cc162107001737b6',
    messagingSenderId: '568688432259',
    projectId: 'lazziapp',
    authDomain: 'lazziapp.firebaseapp.com',
    storageBucket: 'lazziapp.firebasestorage.app',
    measurementId: 'G-4L284993X3',
    databaseURL: 'https://lazziapp-quiz-code-slot.firebaseio.com/',
  );
}
